package(default_visibility = ["//visibility:public"])

exports_files([
    "tool_not_found.tpl.sh",
    "tool_not_found.tpl.bat",
    "merge_static_libs_lnx.tpl.sh",
    "merge_static_libs_win.tpl.bat",
    "dynamic_link_lnx.tpl.sh",
    "dynamic_link_win.tpl.bat",
    "patch_daal_kernel_defines.sh",
    "patch_daal_kernel_defines_win.tpl.bat",
])