name: Code Compliance Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  check-license-header:
    name: Code Sanity
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # - name: "Install Dependencies"
      #   run: |
      #     .ci/env/apt.sh clang-format
      #     .ci/env/editorconfig-checker.sh
      # - name: "ClangFormat Check"
      #   run: .ci/scripts/clang-format.sh
      # - name: "EditorConfig Checker"
      #   run: editorconfig-checker
      - name: Check go.sum
        run: find . -name go.sum
      - name: "Copyright Check"
        uses: apache/skywalking-eyes/header@cd7b195c51fd3d6ad52afceb760719ddc6b3ee91 # v0.6.0
        with:
          config: ".github/.licenserc.yaml"
          mode: "check"
